name = "aturuang-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
MODE = "shadow"

[[d1_databases]]
binding = "DB"
database_name = "aturuang-db"
database_id = "9320692c-3bfa-4782-9aec-23bde74873ac"
